apiVersion: v1
kind: Service
metadata:
  name: hello-node
  labels:
    tag: hello-node
spec:
  ports:
    - port: 8090
      targetPort: 8080
  selector:
    tag: hello-node
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node
  labels:
    tag: hello-node
spec:
  selector:
    matchLabels:
      tag: hello-node
      tier: frontend
  template:
    metadata:
      labels:
        tag: hello-node
        tier: frontend
    spec:
      containers:
      - image: hello-node:v1
        imagePullPolicy: Never
        name: hello-node
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-node
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-node
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

